config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  #get 'home/index'
  get 'home/about'
  root 'friends#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :correct_user,only: [:edit,:update,:destroy]
  
  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = current_user.friends.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :twitter, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <form>
    <div class="mb-3">
      <%= form.label :first_name, style: "display: block",class:"form-label"%>
      <%= form.text_field :first_name, class:"form-control", placeholder:"First name"%>
    </div>

    <div class="mb-3">
      <%= form.label :last_name, style: "display: block" ,class:"form-label"%>
      <%= form.text_field :last_name, class:"form-control", placeholder:"Last name"%>
    </div>

    <div>
      <%= form.label :email, style: "display: block",class:"form-label"%>
      <%= form.text_field :email , class:"form-control", placeholder:"Email"%>
    </div>

    <div>
      <%= form.label :twitter, style: "display: block" ,class:"form-label"%>
      <%= form.text_field :twitter, class:"form-control", placeholder:"Twitter"%>
    </div>

    <div>
      <%= form.label :phone, style: "display: block" ,class:"form-label"%>
      <%= form.text_field :phone, class:"form-control", placeholder:"Phone"%>
    </div>
    <div>
      <%= form.number_field :user_id,id: :friend_user_id, class:"form-control", value:current_user.id,type: :hidden%>
    </div>
    <br>
    <div class="actions">
      <%= form.submit class:"btn btn-secondary"%>
    </div>
  <% end %>
  </form>

app/views/friends/_friend.html.erb
<tr>
  <td><%= link_to friend.first_name  + ' ' + friend.last_name,friend,class:"text-decoration-none"%></td>
  <td><%= friend.email %></td>
  <td><%= friend.twitter %></td>
  <td><%= friend.phone %></td>
  <td><%= friend.user_id%></td>
  <td><%= button_to "Delete", friend, method: :delete ,data:{confirm: "Are you sure"},class:"btn btn-outline-danger btn-sm"%></td>

 
  </tr>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show", @friend ,class:"btn btn-secondary"%> |
  <%= link_to "Back", friends_path ,class:"btn btn-dark"%>
</div>

app/views/friends/index.html.erb
<% if user_signed_in? %>
<h1>Friend List</h1>

<table class = "table table-striped table-hover table-bordered">
  <thead class="table-dark">
    <tr>
      <th scope="col" >Name</th>
      <th scope="col">Email</th>
      <th scope="col">Twitter</th>
      <th scope="col">Phone</th>
      <th scope="col">User Id</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @friends.each do |friend| %>
      <% if friend.user == current_user%>
        <%= render friend %>
      <% end %>
    <% end %>
  </tbody>
</table>


<%= link_to "New friend", new_friend_path, class:"btn btn-secondary"%>
<% else %>
<h1>Hello world</h1>
This is my first Rails Webpage...
<% end %>

app/views/friends/new.html.erb
<h1>Add New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back", friends_path, class:"btn btn-dark" %>
</div>

app/views/friends/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
    <%= @friend.first_name %>
    <%= @friend.last_name %>
  </h1>
  <p class="lead">
    <%= @friend.email %> | <%= @friend.phone %> | <%= @friend.twitter %>
  </p>

  <p class="lead">
    <%= link_to "Edit this friend", edit_friend_path(@friend), class:"btn btn-secondary"%> 
    <%= button_to "Destroy this friend", @friend, method: :delete ,class:"btn btn-secondary"%>
   <br>
    <%= link_to "Back to friends", friends_path,class:"btn btn-dark"%>  
  </p>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <%= link_to 'Friend App', root_path, class:"navbar-brand"%>
        
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <%= link_to 'About Us', home_about_path, class:"nav-link"%>
            </li>
            
            
            <% if user_signed_in? %>
                <li class="nav-item">
                    <%= link_to 'Add Friend', new_friend_path, class:"nav-link"%>
                </li>
                <li class="nav-item">
                    <%= link_to 'Show Friends', friends_path, class:"nav-link"%>
                </li>
                <li class="nav-item">
                    <%= link_to 'Sign Out', destroy_user_session_path,method: :get, class:"nav-link"%>
                </li>
                <li class="nav-item">
                    <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link"%>
                </li>
            <% else %>
                <li class="nav-item">
                    <%= link_to 'Sign Up', new_user_registration_path,method: :POST, class:"nav-link"%>
                </li>
                <li class="nav-item">
                    <%= link_to 'Sign In', new_user_session_path,method: :POST, class:"nav-link"%>
                </li>
            <% end %>
        </ul>
        <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
    </div>
  </nav>

app/views/home/about.html.erb
<h1>About Us...</h1>

app/views/home/index.html.erb
<h1>Hello world</h1>
This is my first Rails Webpage...

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Friends app</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render "home/header" %>
    <br/>
    <div class="container">
    <% if notice %>
      <%= render 'layouts/alerts' %>
    <%end%>
      <br/>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>